/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_interpolate_Interpolation1D */

#ifndef _Included_org_gsl4j_interpolate_Interpolation1D
#define _Included_org_gsl4j_interpolate_Interpolation1D
#ifdef __cplusplus
extern "C" {
#endif
#undef org_gsl4j_interpolate_Interpolation1D_LINEAR
#define org_gsl4j_interpolate_Interpolation1D_LINEAR 0L
#undef org_gsl4j_interpolate_Interpolation1D_POLYNOMIAL
#define org_gsl4j_interpolate_Interpolation1D_POLYNOMIAL 1L
#undef org_gsl4j_interpolate_Interpolation1D_CUBIC_SPLINE
#define org_gsl4j_interpolate_Interpolation1D_CUBIC_SPLINE 2L
#undef org_gsl4j_interpolate_Interpolation1D_CUBIC_SPLINE_PERIODIC
#define org_gsl4j_interpolate_Interpolation1D_CUBIC_SPLINE_PERIODIC 3L
#undef org_gsl4j_interpolate_Interpolation1D_AKIMA
#define org_gsl4j_interpolate_Interpolation1D_AKIMA 4L
#undef org_gsl4j_interpolate_Interpolation1D_AKIMA_PERIODIC
#define org_gsl4j_interpolate_Interpolation1D_AKIMA_PERIODIC 5L
#undef org_gsl4j_interpolate_Interpolation1D_STEFFEN
#define org_gsl4j_interpolate_Interpolation1D_STEFFEN 6L
/*
 * Class:     org_gsl4j_interpolate_Interpolation1D
 * Method:    cacheData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_interpolate_Interpolation1D_cacheData
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gsl4j_interpolate_Interpolation1D
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gsl4j_interpolate_Interpolation1D_name
  (JNIEnv *, jobject);

/*
 * Class:     org_gsl4j_interpolate_Interpolation1D
 * Method:    minSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gsl4j_interpolate_Interpolation1D_minSize
  (JNIEnv *, jobject);

/*
 * Class:     org_gsl4j_interpolate_Interpolation1D
 * Method:    eval
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_interpolate_Interpolation1D_eval__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_interpolate_Interpolation1D
 * Method:    eval
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_interpolate_Interpolation1D_eval___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_interpolate_Interpolation1D
 * Method:    deriv
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_interpolate_Interpolation1D_deriv__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_interpolate_Interpolation1D
 * Method:    deriv
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_interpolate_Interpolation1D_deriv___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_interpolate_Interpolation1D
 * Method:    deriv2
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_interpolate_Interpolation1D_deriv2__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_interpolate_Interpolation1D
 * Method:    deriv2
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_interpolate_Interpolation1D_deriv2___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_interpolate_Interpolation1D
 * Method:    integrate
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_interpolate_Interpolation1D_integrate
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
