/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_polynom_HermitePolynom */

#ifndef _Included_org_gsl4j_polynom_HermitePolynom
#define _Included_org_gsl4j_polynom_HermitePolynom
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermite
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermite
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteArray
 * Signature: (ID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteArray
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteSeries
 * Signature: (ID[D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteSeries
  (JNIEnv *, jclass, jint, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteProb
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteProb
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteProbArray
 * Signature: (ID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteProbArray
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteProbSeries
 * Signature: (ID[D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteProbSeries
  (JNIEnv *, jclass, jint, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteDeriv
 * Signature: (IID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteDeriv
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteArrayDeriv
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteArrayDeriv
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteDerivArray
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteDerivArray
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteProbDeriv
 * Signature: (IID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteProbDeriv
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteProbArrayDeriv
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteProbArrayDeriv
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteProbDerivArray
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteProbDerivArray
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteZero
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteZero
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_gsl4j_polynom_HermitePolynom
 * Method:    hermiteProbZero
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_polynom_HermitePolynom_hermiteProbZero
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
