/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_complex_ComplexMath */

#ifndef _Included_org_gsl4j_complex_ComplexMath
#define _Included_org_gsl4j_complex_ComplexMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arg
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_complex_ComplexMath_arg
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    abs
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_complex_ComplexMath_abs
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    abs2
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_complex_ComplexMath_abs2
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    logabs
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_complex_ComplexMath_logabs
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    add
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_add
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    sub
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_sub
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    mul
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_mul
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    div
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_div
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    addReal
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_addReal
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    subReal
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_subReal
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    mulReal
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_mulReal
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    divReal
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_divReal
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    addImag
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_addImag
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    subImag
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_subImag
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    mulImag
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_mulImag
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    divImag
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_divImag
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    conjugate
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_conjugate
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    inverse
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_inverse
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    negative
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_negative
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    sqrt
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_sqrt
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    sqrtReal
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_sqrtReal
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    pow
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_pow
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    powReal
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_powReal
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    exp
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_exp
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    log
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_log
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    log10
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_log10
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    logb
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_logb
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    sin
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_sin
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    cos
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_cos
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    tan
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_tan
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    sec
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_sec
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    csc
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_csc
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    cot
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_cot
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arcsin
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arcsin
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arcsinReal
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arcsinReal
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arccos
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arccos
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arccosReal
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arccosReal
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arctan
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arctan
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arcsec
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arcsec
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arcsecReal
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arcsecReal
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arccsc
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arccsc
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arccscReal
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arccscReal
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arccot
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arccot
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    sinh
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_sinh
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    cosh
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_cosh
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    tanh
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_tanh
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    sech
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_sech
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    csch
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_csch
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    coth
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_coth
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arcsinh
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arcsinh
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arccosh
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arccosh
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arccoshReal
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arccoshReal
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arctanh
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arctanh
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arctanhReal
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arctanhReal
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arcsech
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arcsech
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arccsch
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arccsch
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_complex_ComplexMath
 * Method:    arccoth
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_complex_ComplexMath_arccoth
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
