/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_Dilogarithm */

#ifndef _Included_org_gsl4j_special_Dilogarithm
#define _Included_org_gsl4j_special_Dilogarithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_Dilogarithm
 * Method:    dilog
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Dilogarithm_dilog__D
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Dilogarithm
 * Method:    dilog
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_Dilogarithm_dilog__DD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Dilogarithm
 * Method:    dilogPolar
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_Dilogarithm_dilogPolar
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
