/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_MathConstants */

#ifndef _Included_org_gsl4j_MathConstants
#define _Included_org_gsl4j_MathConstants
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_MathConstants
 * Method:    me
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_me
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    mlog2e
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_mlog2e
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    mlog10e
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_mlog10e
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    msqrt2
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_msqrt2
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    msqrt12
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_msqrt12
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    msqrt3
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_msqrt3
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    mpi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_mpi
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    mpi2
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_mpi2
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    mpi4
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_mpi4
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    msqrtpi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_msqrtpi
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    m2sqrtpi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_m2sqrtpi
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    m1pi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_m1pi
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    m2pi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_m2pi
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    mln10
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_mln10
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    mln2
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_mln2
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    mlnpi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_mlnpi
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    meuler
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_meuler
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    gslposinf
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_gslposinf
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    gslneginf
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_gslneginf
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    gslnan
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_MathConstants_gslnan
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    isNaN
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gsl4j_MathConstants_isNaN
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    isInf
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gsl4j_MathConstants_isInf
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    isPositiveInf
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gsl4j_MathConstants_isPositiveInf
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    isNegativeInf
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gsl4j_MathConstants_isNegativeInf
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_MathConstants
 * Method:    isFinite
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gsl4j_MathConstants_isFinite
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
