/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_Transport */

#ifndef _Included_org_gsl4j_special_Transport
#define _Included_org_gsl4j_special_Transport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_Transport
 * Method:    transport2
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Transport_transport2
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Transport
 * Method:    transport3
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Transport_transport3
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Transport
 * Method:    transport4
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Transport_transport4
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Transport
 * Method:    transport5
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Transport_transport5
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
