/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_ErrorFunction */

#ifndef _Included_org_gsl4j_special_ErrorFunction
#define _Included_org_gsl4j_special_ErrorFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_ErrorFunction
 * Method:    erf
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ErrorFunction_erf
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ErrorFunction
 * Method:    erfc
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ErrorFunction_erfc
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ErrorFunction
 * Method:    logErfc
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ErrorFunction_logErfc
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ErrorFunction
 * Method:    erfZ
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ErrorFunction_erfZ
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ErrorFunction
 * Method:    erfQ
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ErrorFunction_erfQ
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ErrorFunction
 * Method:    hazard
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ErrorFunction_hazard
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
