/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_EllipticIntegrals */

#ifndef _Included_org_gsl4j_special_EllipticIntegrals
#define _Included_org_gsl4j_special_EllipticIntegrals
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    ellintKcomp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_ellintKcomp
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    ellintEcomp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_ellintEcomp
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    ellintPcomp
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_ellintPcomp
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    ellintF
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_ellintF
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    ellintE
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_ellintE
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    ellintP
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_ellintP
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    ellintD
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_ellintD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    ellintRC
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_ellintRC
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    ellintRD
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_ellintRD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    ellintRF
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_ellintRF
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    ellintRJ
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_ellintRJ
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    elljacSn
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_elljacSn
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    elljacCn
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_elljacCn
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    elljacDn
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_EllipticIntegrals_elljacDn
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_EllipticIntegrals
 * Method:    elljac
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_EllipticIntegrals_elljac
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
