/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_Dawson */

#ifndef _Included_org_gsl4j_special_Dawson
#define _Included_org_gsl4j_special_Dawson
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_Dawson
 * Method:    dawson
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Dawson_dawson
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
