/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_Airy */

#ifndef _Included_org_gsl4j_special_Airy
#define _Included_org_gsl4j_special_Airy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_Airy
 * Method:    ai
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Airy_ai
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Airy
 * Method:    aiScaled
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Airy_aiScaled
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Airy
 * Method:    aiDeriv
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Airy_aiDeriv
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Airy
 * Method:    aiDerivScaled
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Airy_aiDerivScaled
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Airy
 * Method:    aiZero
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Airy_aiZero
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Airy
 * Method:    aiDerivZero
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Airy_aiDerivZero
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Airy
 * Method:    bi
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Airy_bi
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Airy
 * Method:    biScaled
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Airy_biScaled
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Airy
 * Method:    biDeriv
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Airy_biDeriv
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Airy
 * Method:    biDerivScaled
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Airy_biDerivScaled
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Airy
 * Method:    biZero
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Airy_biZero
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Airy
 * Method:    biDerivZero
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Airy_biDerivZero
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
