/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_Hermite */

#ifndef _Included_org_gsl4j_special_Hermite
#define _Included_org_gsl4j_special_Hermite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_Hermite
 * Method:    hermiteFunc
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Hermite_hermiteFunc
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_gsl4j_special_Hermite
 * Method:    hermiteFuncFast
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Hermite_hermiteFuncFast
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_gsl4j_special_Hermite
 * Method:    hermiteFuncArray
 * Signature: (ID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_Hermite_hermiteFuncArray
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_gsl4j_special_Hermite
 * Method:    hermiteFuncSeries
 * Signature: (ID[D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Hermite_hermiteFuncSeries
  (JNIEnv *, jclass, jint, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_special_Hermite
 * Method:    hermiteFuncDeriv
 * Signature: (IID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Hermite_hermiteFuncDeriv
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_gsl4j_special_Hermite
 * Method:    hermiteFuncZero
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Hermite_hermiteFuncZero
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
