/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_FermiDirac */

#ifndef _Included_org_gsl4j_special_FermiDirac
#define _Included_org_gsl4j_special_FermiDirac
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_FermiDirac
 * Method:    fermiDiracM1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_FermiDirac_fermiDiracM1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_FermiDirac
 * Method:    fermiDriac0
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_FermiDirac_fermiDriac0
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_FermiDirac
 * Method:    fermiDirac1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_FermiDirac_fermiDirac1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_FermiDirac
 * Method:    fermiDirac2
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_FermiDirac_fermiDirac2
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_FermiDirac
 * Method:    fermiDiracInt
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_FermiDirac_fermiDiracInt
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_gsl4j_special_FermiDirac
 * Method:    fermiDiracMhalf
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_FermiDirac_fermiDiracMhalf
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_FermiDirac
 * Method:    fermiDiractHalf
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_FermiDirac_fermiDiractHalf
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_FermiDirac
 * Method:    fermiDirac3half
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_FermiDirac_fermiDirac3half
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_FermiDirac
 * Method:    fermiDiractIncomplete0
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_FermiDirac_fermiDiractIncomplete0
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
