/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_ExpFunction */

#ifndef _Included_org_gsl4j_special_ExpFunction
#define _Included_org_gsl4j_special_ExpFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_ExpFunction
 * Method:    exp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpFunction_exp
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpFunction
 * Method:    exp10
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpFunction_exp10
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpFunction
 * Method:    expMult
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpFunction_expMult
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_ExpFunction
 * Method:    multE10
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpFunction_multE10
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_ExpFunction
 * Method:    expm1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpFunction_expm1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpFunction
 * Method:    exprel
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpFunction_exprel
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpFunction
 * Method:    exprel2
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpFunction_exprel2
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpFunction
 * Method:    exprelN
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpFunction_exprelN
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_gsl4j_special_ExpFunction
 * Method:    expErr
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_ExpFunction_expErr
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_ExpFunction
 * Method:    expErrE10
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_ExpFunction_expErrE10
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_ExpFunction
 * Method:    expMultErr
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_ExpFunction_expMultErr
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_ExpFunction
 * Method:    expMultErrE10
 * Signature: (DDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_ExpFunction_expMultErrE10
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
