/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_ode_OdeSolver */

#ifndef _Included_org_gsl4j_ode_OdeSolver
#define _Included_org_gsl4j_ode_OdeSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_ode_OdeSolver_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rk2
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ode_OdeSolver_rk2__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rk2
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_ode_OdeSolver_rk2___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rk4
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ode_OdeSolver_rk4__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rk4
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_ode_OdeSolver_rk4___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rkf45
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ode_OdeSolver_rkf45__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rkf45
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_ode_OdeSolver_rkf45___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rkck
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ode_OdeSolver_rkck__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rkck
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_ode_OdeSolver_rkck___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rk8pd
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ode_OdeSolver_rk8pd__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rk8pd
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_ode_OdeSolver_rk8pd___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rk1imp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ode_OdeSolver_rk1imp__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rk1imp
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_ode_OdeSolver_rk1imp___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rk2imp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ode_OdeSolver_rk2imp__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rk2imp
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_ode_OdeSolver_rk2imp___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rk4imp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ode_OdeSolver_rk4imp__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    rk4imp
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_ode_OdeSolver_rk4imp___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    bsimp
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ode_OdeSolver_bsimp__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    bsimp
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_ode_OdeSolver_bsimp___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    msadams
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ode_OdeSolver_msadams__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    msadams
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_ode_OdeSolver_msadams___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    msbdf
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ode_OdeSolver_msbdf__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_ode_OdeSolver
 * Method:    msbdf
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_ode_OdeSolver_msbdf___3D
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
