/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_integration_Integral1D */

#ifndef _Included_org_gsl4j_integration_Integral1D
#define _Included_org_gsl4j_integration_Integral1D
#ifdef __cplusplus
extern "C" {
#endif
#undef org_gsl4j_integration_Integral1D_WEIGHT_FUNC_TYPE_I
#define org_gsl4j_integration_Integral1D_WEIGHT_FUNC_TYPE_I 100L
#undef org_gsl4j_integration_Integral1D_WEIGHT_FUNC_TYPE_II
#define org_gsl4j_integration_Integral1D_WEIGHT_FUNC_TYPE_II 101L
#undef org_gsl4j_integration_Integral1D_WEIGHT_FUNC_TYPE_III
#define org_gsl4j_integration_Integral1D_WEIGHT_FUNC_TYPE_III 102L
#undef org_gsl4j_integration_Integral1D_WEIGHT_FUNC_TYPE_IV
#define org_gsl4j_integration_Integral1D_WEIGHT_FUNC_TYPE_IV 103L
#undef org_gsl4j_integration_Integral1D_GSL_INTEG_COSINE
#define org_gsl4j_integration_Integral1D_GSL_INTEG_COSINE 0L
#undef org_gsl4j_integration_Integral1D_GSL_INTEG_SINE
#define org_gsl4j_integration_Integral1D_GSL_INTEG_SINE 1L
#undef org_gsl4j_integration_Integral1D_FIXED_LEGENDRE
#define org_gsl4j_integration_Integral1D_FIXED_LEGENDRE 2L
#undef org_gsl4j_integration_Integral1D_FIXED_CHEBYSHEV
#define org_gsl4j_integration_Integral1D_FIXED_CHEBYSHEV 3L
#undef org_gsl4j_integration_Integral1D_FIXED_GEGENBAUER
#define org_gsl4j_integration_Integral1D_FIXED_GEGENBAUER 4L
#undef org_gsl4j_integration_Integral1D_FIXED_JACOBI
#define org_gsl4j_integration_Integral1D_FIXED_JACOBI 5L
#undef org_gsl4j_integration_Integral1D_FIXED_LAGUERRE
#define org_gsl4j_integration_Integral1D_FIXED_LAGUERRE 6L
#undef org_gsl4j_integration_Integral1D_FIXED_HERMITE
#define org_gsl4j_integration_Integral1D_FIXED_HERMITE 7L
#undef org_gsl4j_integration_Integral1D_FIXED_EXPONENTIAL
#define org_gsl4j_integration_Integral1D_FIXED_EXPONENTIAL 8L
#undef org_gsl4j_integration_Integral1D_FIXED_RATIONAL
#define org_gsl4j_integration_Integral1D_FIXED_RATIONAL 9L
#undef org_gsl4j_integration_Integral1D_FIXED_CHEBYSHEV2
#define org_gsl4j_integration_Integral1D_FIXED_CHEBYSHEV2 10L
/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    initFieldIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_integration_Integral1D_initFieldIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qng
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qng
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qngDetailed
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qngDetailed
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagGauss15
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qagGauss15
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagGauss15withError
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qagGauss15withError
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagGauss21
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qagGauss21
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagGauss21withError
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qagGauss21withError
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagGauss31
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qagGauss31
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagGauss31withError
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qagGauss31withError
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagGauss41
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qagGauss41
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagGauss41withError
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qagGauss41withError
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagGauss51
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qagGauss51
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagGauss51withError
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qagGauss51withError
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagGauss61
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qagGauss61
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagGauss61withError
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qagGauss61withError
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qags
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qags
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagsWithError
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qagsWithError
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagp
 * Signature: (DD[D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qagp
  (JNIEnv *, jobject, jdouble, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagpWithError
 * Signature: (DD[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qagpWithError
  (JNIEnv *, jobject, jdouble, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagi
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qagi
  (JNIEnv *, jobject);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagiWithError
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qagiWithError
  (JNIEnv *, jobject);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagiu
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qagiu
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagiuWithError
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qagiuWithError
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagil
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qagil
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qagilWithError
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qagilWithError
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qawc
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qawc
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qawcWithError
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qawcWithError
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qaws
 * Signature: (DDIDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qaws
  (JNIEnv *, jobject, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qawsWithError
 * Signature: (DDIDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qawsWithError
  (JNIEnv *, jobject, jdouble, jdouble, jint, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qawo
 * Signature: (DDID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qawo
  (JNIEnv *, jobject, jdouble, jdouble, jint, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qawoWithError
 * Signature: (DDID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qawoWithError
  (JNIEnv *, jobject, jdouble, jdouble, jint, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qawf
 * Signature: (DID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qawf
  (JNIEnv *, jobject, jdouble, jint, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qawfWithError
 * Signature: (DID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qawfWithError
  (JNIEnv *, jobject, jdouble, jint, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    cquad
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_cquad
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    cquadWithError
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_cquadWithError
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    romberg
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_romberg
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    rombergDetailed
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_rombergDetailed
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    glfixed
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_glfixed
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    glfixedPointAndWeight
 * Signature: (DDII)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_glfixedPointAndWeight
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qfixed
 * Signature: (DDIIDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_integration_Integral1D_qfixed
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qfixedPoints
 * Signature: (DDIIDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qfixedPoints
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint, jdouble, jdouble);

/*
 * Class:     org_gsl4j_integration_Integral1D
 * Method:    qfixedWeights
 * Signature: (DDIIDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_integration_Integral1D_qfixedWeights
  (JNIEnv *, jobject, jdouble, jdouble, jint, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
