/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_Zeta */

#ifndef _Included_org_gsl4j_special_Zeta
#define _Included_org_gsl4j_special_Zeta
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_Zeta
 * Method:    zetaInt
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Zeta_zetaInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Zeta
 * Method:    zeta
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Zeta_zeta
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Zeta
 * Method:    zetam1Int
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Zeta_zetam1Int
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Zeta
 * Method:    zetam1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Zeta_zetam1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Zeta
 * Method:    hzeta
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Zeta_hzeta
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Zeta
 * Method:    etaInt
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Zeta_etaInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Zeta
 * Method:    eta
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Zeta_eta
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
