/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_Gegenbauer */

#ifndef _Included_org_gsl4j_special_Gegenbauer
#define _Included_org_gsl4j_special_Gegenbauer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_Gegenbauer
 * Method:    gegenpoly1
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gegenbauer_gegenpoly1
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gegenbauer
 * Method:    gegenpoly2
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gegenbauer_gegenpoly2
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gegenbauer
 * Method:    gegenpoly3
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gegenbauer_gegenpoly3
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gegenbauer
 * Method:    gegenpolyN
 * Signature: (IDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gegenbauer_gegenpolyN
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gegenbauer
 * Method:    gegenpolyArray
 * Signature: (IDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_Gegenbauer_gegenpolyArray
  (JNIEnv *, jclass, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
