/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_Synchrotron */

#ifndef _Included_org_gsl4j_special_Synchrotron
#define _Included_org_gsl4j_special_Synchrotron
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_Synchrotron
 * Method:    synchrotron1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Synchrotron_synchrotron1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Synchrotron
 * Method:    synchrotron2
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Synchrotron_synchrotron2
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
