/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_ExpIntegrals */

#ifndef _Included_org_gsl4j_special_ExpIntegrals
#define _Included_org_gsl4j_special_ExpIntegrals
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_ExpIntegrals
 * Method:    expIntE1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpIntegrals_expIntE1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpIntegrals
 * Method:    expIntE2
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpIntegrals_expIntE2
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpIntegrals
 * Method:    expIntEn
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpIntegrals_expIntEn
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_gsl4j_special_ExpIntegrals
 * Method:    expIntEi
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpIntegrals_expIntEi
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpIntegrals
 * Method:    shi
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpIntegrals_shi
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpIntegrals
 * Method:    chi
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpIntegrals_chi
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpIntegrals
 * Method:    expInt3
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpIntegrals_expInt3
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpIntegrals
 * Method:    si
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpIntegrals_si
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpIntegrals
 * Method:    ci
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpIntegrals_ci
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_ExpIntegrals
 * Method:    atanInt
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_ExpIntegrals_atanInt
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
