/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_ElementaryFunctions */

#ifndef _Included_org_gsl4j_ElementaryFunctions
#define _Included_org_gsl4j_ElementaryFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    log1p
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_log1p
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    expm1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_expm1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    hypot
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_hypot
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    hypot3
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_hypot3
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    acosh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_acosh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    asinh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_asinh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    atanh
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_atanh
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    ldexp
 * Signature: (DI)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_ldexp
  (JNIEnv *, jclass, jdouble, jint);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    frexp
 * Signature: (DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_ElementaryFunctions_frexp
  (JNIEnv *, jclass, jdouble, jint);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    powInt
 * Signature: (DI)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_powInt
  (JNIEnv *, jclass, jdouble, jint);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    pow2
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_pow2
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    pow3
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_pow3
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    pow4
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_pow4
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    pow5
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_pow5
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    pow6
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_pow6
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    pow7
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_pow7
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    pow8
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_pow8
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    pow9
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_pow9
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    sign
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_org_gsl4j_ElementaryFunctions_sign
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    isOdd
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gsl4j_ElementaryFunctions_isOdd
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    isEven
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gsl4j_ElementaryFunctions_isEven
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    max
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_max
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    min
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_min
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    fcmp
 * Signature: (DDD)I
 */
JNIEXPORT jint JNICALL Java_org_gsl4j_ElementaryFunctions_fcmp
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_multiply
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_ElementaryFunctions
 * Method:    multiplyError
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_ElementaryFunctions_multiplyError
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
