/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_Gamma */

#ifndef _Included_org_gsl4j_special_Gamma
#define _Included_org_gsl4j_special_Gamma
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    gamma
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_gamma
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    lngamma
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_lngamma
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    lngammaSign
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_Gamma_lngammaSign
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    gammaStar
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_gammaStar
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    gammaInv
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_gammaInv
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    lngammaComplex
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_Gamma_lngammaComplex
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    factorial
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_factorial
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    doubleFactorial
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_doubleFactorial
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    lnfactorial
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_lnfactorial
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    lnDoubleFactorial
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_lnDoubleFactorial
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    choose
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_choose
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    lnchoose
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_lnchoose
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    taylorCoeff
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_taylorCoeff
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    poch
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_poch
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    lnpoch
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_lnpoch
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    lnpochSign
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_Gamma_lnpochSign
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    pochrel
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_pochrel
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    gammaIncomplete
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_gammaIncomplete
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    gammaIncompleteQ
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_gammaIncompleteQ
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    gammaIncompleteP
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_gammaIncompleteP
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    beta
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_beta
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    lnbeta
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_lnbeta
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Gamma
 * Method:    betaIncomplete
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Gamma_betaIncomplete
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
