/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_optimize_Minimize */

#ifndef _Included_org_gsl4j_optimize_Minimize
#define _Included_org_gsl4j_optimize_Minimize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_optimize_Minimize
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_optimize_Minimize_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_gsl4j_optimize_Minimize
 * Method:    goldenSection
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_optimize_Minimize_goldenSection
  (JNIEnv *, jobject);

/*
 * Class:     org_gsl4j_optimize_Minimize
 * Method:    brent
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_optimize_Minimize_brent
  (JNIEnv *, jobject);

/*
 * Class:     org_gsl4j_optimize_Minimize
 * Method:    quadGolden
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_optimize_Minimize_quadGolden
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
