/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_Digamma */

#ifndef _Included_org_gsl4j_special_Digamma
#define _Included_org_gsl4j_special_Digamma
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_Digamma
 * Method:    psiInt
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Digamma_psiInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Digamma
 * Method:    digamma
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Digamma_digamma__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Digamma
 * Method:    psi
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Digamma_psi
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Digamma
 * Method:    digamma
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Digamma_digamma__D
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Digamma
 * Method:    psi1piy
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Digamma_psi1piy
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Digamma
 * Method:    psi1int
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Digamma_psi1int
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_gsl4j_special_Digamma
 * Method:    psi1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Digamma_psi1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Digamma
 * Method:    trigamma
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Digamma_trigamma
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Digamma
 * Method:    psiN
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Digamma_psiN
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     org_gsl4j_special_Digamma
 * Method:    polygamma
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Digamma_polygamma
  (JNIEnv *, jclass, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
