/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_Logarithm */

#ifndef _Included_org_gsl4j_special_Logarithm
#define _Included_org_gsl4j_special_Logarithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_Logarithm
 * Method:    log
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Logarithm_log
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Logarithm
 * Method:    logAbs
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Logarithm_logAbs
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Logarithm
 * Method:    complexLog
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_Logarithm_complexLog
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Logarithm
 * Method:    log1plusx
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Logarithm_log1plusx
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     org_gsl4j_special_Logarithm
 * Method:    log1plusxMx
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Logarithm_log1plusxMx
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
