/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_vector_VectorMath */

#ifndef _Included_org_gsl4j_vector_VectorMath
#define _Included_org_gsl4j_vector_VectorMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    add
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_add___3D_3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    sub
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_sub___3D_3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    mul
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_mul___3D_3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    div
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_div___3D_3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    addRev
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_addRev___3D_3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    subRev
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_subRev___3D_3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    mulRev
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_mulRev___3D_3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    divRev
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_divRev___3D_3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    add
 * Signature: ([DD[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_add___3DD_3D
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    sub
 * Signature: ([DD[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_sub___3DD_3D
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    mul
 * Signature: ([DD[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_mul___3DD_3D
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    div
 * Signature: ([DD[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_div___3DD_3D
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    addRev
 * Signature: ([DD[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_addRev___3DD_3D
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    subRev
 * Signature: ([DD[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_subRev___3DD_3D
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    mulRev
 * Signature: ([DD[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_mulRev___3DD_3D
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    divRev
 * Signature: ([DD[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_divRev___3DD_3D
  (JNIEnv *, jclass, jdoubleArray, jdouble, jdoubleArray);

/*
 * Class:     org_gsl4j_vector_VectorMath
 * Method:    axpby
 * Signature: (D[DD[D[D)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_vector_VectorMath_axpby
  (JNIEnv *, jclass, jdouble, jdoubleArray, jdouble, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
