/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_HyperGeometric */

#ifndef _Included_org_gsl4j_special_HyperGeometric
#define _Included_org_gsl4j_special_HyperGeometric
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_HyperGeometric
 * Method:    hyperg0F1
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_HyperGeometric_hyperg0F1
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_HyperGeometric
 * Method:    hyperg1F1int
 * Signature: (IID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_HyperGeometric_hyperg1F1int
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_gsl4j_special_HyperGeometric
 * Method:    hyperg1F1
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_HyperGeometric_hyperg1F1
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_HyperGeometric
 * Method:    hypergUint
 * Signature: (IID)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_HyperGeometric_hypergUint
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_gsl4j_special_HyperGeometric
 * Method:    hypergUintE10
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_HyperGeometric_hypergUintE10
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     org_gsl4j_special_HyperGeometric
 * Method:    hypergU
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_HyperGeometric_hypergU
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_HyperGeometric
 * Method:    hypergUe10
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_special_HyperGeometric_hypergUe10
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_HyperGeometric
 * Method:    hyperg2F1
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_HyperGeometric_hyperg2F1
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_HyperGeometric
 * Method:    hyperg2F1conj
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_HyperGeometric_hyperg2F1conj
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_HyperGeometric
 * Method:    hyperg2F1renorm
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_HyperGeometric_hyperg2F1renorm
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_HyperGeometric
 * Method:    hyperg2F1conjRenorm
 * Signature: (DDDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_HyperGeometric_hyperg2F1conjRenorm
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_HyperGeometric
 * Method:    hyperg2F0
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_HyperGeometric_hyperg2F0
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
