/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_sequence_LevinTransform */

#ifndef _Included_org_gsl4j_sequence_LevinTransform
#define _Included_org_gsl4j_sequence_LevinTransform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_sequence_LevinTransform
 * Method:    sumLevinUaccel
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_sequence_LevinTransform_sumLevinUaccel
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     org_gsl4j_sequence_LevinTransform
 * Method:    sumLevinUtruncAccel
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_gsl4j_sequence_LevinTransform_sumLevinUtruncAccel
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
