/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_special_Laguerre */

#ifndef _Included_org_gsl4j_special_Laguerre
#define _Included_org_gsl4j_special_Laguerre
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gsl4j_special_Laguerre
 * Method:    laguerre1
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Laguerre_laguerre1
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Laguerre
 * Method:    laguerre2
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Laguerre_laguerre2
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Laguerre
 * Method:    laguerre3
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Laguerre_laguerre3
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     org_gsl4j_special_Laguerre
 * Method:    laguerreN
 * Signature: (IDD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_special_Laguerre_laguerreN
  (JNIEnv *, jclass, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
