/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gsl4j_interpolate_Interpolation2D */

#ifndef _Included_org_gsl4j_interpolate_Interpolation2D
#define _Included_org_gsl4j_interpolate_Interpolation2D
#ifdef __cplusplus
extern "C" {
#endif
#undef org_gsl4j_interpolate_Interpolation2D_BILINEAR
#define org_gsl4j_interpolate_Interpolation2D_BILINEAR 0L
#undef org_gsl4j_interpolate_Interpolation2D_BICUBIC
#define org_gsl4j_interpolate_Interpolation2D_BICUBIC 1L
/*
 * Class:     org_gsl4j_interpolate_Interpolation2D
 * Method:    cacheData
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_gsl4j_interpolate_Interpolation2D_cacheData
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_gsl4j_interpolate_Interpolation2D
 * Method:    name
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_gsl4j_interpolate_Interpolation2D_name
  (JNIEnv *, jobject);

/*
 * Class:     org_gsl4j_interpolate_Interpolation2D
 * Method:    minSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_gsl4j_interpolate_Interpolation2D_minSize
  (JNIEnv *, jobject);

/*
 * Class:     org_gsl4j_interpolate_Interpolation2D
 * Method:    eval
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_interpolate_Interpolation2D_eval
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_interpolate_Interpolation2D
 * Method:    derivX
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_interpolate_Interpolation2D_derivX
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_interpolate_Interpolation2D
 * Method:    derivY
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_interpolate_Interpolation2D_derivY
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_interpolate_Interpolation2D
 * Method:    derivXX
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_interpolate_Interpolation2D_derivXX
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_interpolate_Interpolation2D
 * Method:    derivYY
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_interpolate_Interpolation2D_derivYY
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_interpolate_Interpolation2D
 * Method:    derivXY
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_interpolate_Interpolation2D_derivXY
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     org_gsl4j_interpolate_Interpolation2D
 * Method:    derivYX
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_org_gsl4j_interpolate_Interpolation2D_derivYX
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
