/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_simd4j_ArrayMath */

#ifndef _Included_org_simd4j_ArrayMath
#define _Included_org_simd4j_ArrayMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_simd4j_ArrayMath
 * Method:    add
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_org_simd4j_ArrayMath_add___3I_3I_3I
  (JNIEnv *, jclass, jintArray, jintArray, jintArray);

/*
 * Class:     org_simd4j_ArrayMath
 * Method:    sub
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_org_simd4j_ArrayMath_sub___3I_3I_3I
  (JNIEnv *, jclass, jintArray, jintArray, jintArray);

/*
 * Class:     org_simd4j_ArrayMath
 * Method:    mul
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_org_simd4j_ArrayMath_mul___3I_3I_3I
  (JNIEnv *, jclass, jintArray, jintArray, jintArray);

/*
 * Class:     org_simd4j_ArrayMath
 * Method:    div
 * Signature: ([I[I[I)V
 */
JNIEXPORT void JNICALL Java_org_simd4j_ArrayMath_div___3I_3I_3I
  (JNIEnv *, jclass, jintArray, jintArray, jintArray);

/*
 * Class:     org_simd4j_ArrayMath
 * Method:    add
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_org_simd4j_ArrayMath_add___3F_3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     org_simd4j_ArrayMath
 * Method:    sub
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_org_simd4j_ArrayMath_sub___3F_3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     org_simd4j_ArrayMath
 * Method:    mul
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_org_simd4j_ArrayMath_mul___3F_3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     org_simd4j_ArrayMath
 * Method:    div
 * Signature: ([F[F[F)V
 */
JNIEXPORT void JNICALL Java_org_simd4j_ArrayMath_div___3F_3F_3F
  (JNIEnv *, jclass, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     org_simd4j_ArrayMath
 * Method:    add
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_org_simd4j_ArrayMath_add___3D_3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_simd4j_ArrayMath
 * Method:    sub
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_org_simd4j_ArrayMath_sub___3D_3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_simd4j_ArrayMath
 * Method:    mul
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_org_simd4j_ArrayMath_mul___3D_3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     org_simd4j_ArrayMath
 * Method:    div
 * Signature: ([D[D[D)V
 */
JNIEXPORT void JNICALL Java_org_simd4j_ArrayMath_div___3D_3D_3D
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
