/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func4j_special_Debye */

#ifndef _Included_func4j_special_Debye
#define _Included_func4j_special_Debye
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func4j_special_Debye
 * Method:    debye1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Debye_debye1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Debye
 * Method:    debye2
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Debye_debye2
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Debye
 * Method:    debye3
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Debye_debye3
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Debye
 * Method:    debye4
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Debye_debye4
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Debye
 * Method:    debye5
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Debye_debye5
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Debye
 * Method:    debye6
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Debye_debye6
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
