/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func4j_roots_MultiRoot */

#ifndef _Included_func4j_roots_MultiRoot
#define _Included_func4j_roots_MultiRoot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func4j_roots_MultiRoot
 * Method:    initFieldIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_func4j_roots_MultiRoot_initFieldIDs
  (JNIEnv *, jclass);

/*
 * Class:     func4j_roots_MultiRoot
 * Method:    hybridsj
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_roots_MultiRoot_hybridsj
  (JNIEnv *, jobject);

/*
 * Class:     func4j_roots_MultiRoot
 * Method:    hybridj
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_roots_MultiRoot_hybridj
  (JNIEnv *, jobject);

/*
 * Class:     func4j_roots_MultiRoot
 * Method:    newton
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_roots_MultiRoot_newton
  (JNIEnv *, jobject);

/*
 * Class:     func4j_roots_MultiRoot
 * Method:    gnewton
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_roots_MultiRoot_gnewton
  (JNIEnv *, jobject);

/*
 * Class:     func4j_roots_MultiRoot
 * Method:    hybrids
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_roots_MultiRoot_hybrids
  (JNIEnv *, jobject);

/*
 * Class:     func4j_roots_MultiRoot
 * Method:    hybrid
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_roots_MultiRoot_hybrid
  (JNIEnv *, jobject);

/*
 * Class:     func4j_roots_MultiRoot
 * Method:    dnewton
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_roots_MultiRoot_dnewton
  (JNIEnv *, jobject);

/*
 * Class:     func4j_roots_MultiRoot
 * Method:    broyden
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_roots_MultiRoot_broyden
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
