/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func4j_special_Bessel */

#ifndef _Included_func4j_special_Bessel
#define _Included_func4j_special_Bessel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func4j_special_Bessel
 * Method:    J0
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_J0
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    J1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_J1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Jn
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_Jn__ID
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    JnArray
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_JnArray
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Y0
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_Y0
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Y1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_Y1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Yn
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_Yn__ID
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    YnArray
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_YnArray
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    I0
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_I0
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    I1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_I1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    In
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_In__ID
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    InArray
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_InArray
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    I0Scaled
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_I0Scaled
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    I1Scaled
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_I1Scaled
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    InScaled
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_InScaled
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    InScaledArray
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_InScaledArray
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    K0
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_K0
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    K1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_K1
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Kn
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_Kn__ID
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    KnArray
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_KnArray
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    K0Scaled
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_K0Scaled
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    K1Scaled
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_K1Scaled
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    KnScaled
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_KnScaled
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    KnScaledArray
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_KnScaledArray
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Jv
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_Jv__DD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Jv
 * Signature: (D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_Jv__D_3D
  (JNIEnv *, jclass, jdouble, jdoubleArray);

/*
 * Class:     func4j_special_Bessel
 * Method:    Yv
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_Yv__DD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Iv
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_Iv__DD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    IvScaled
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_IvScaled
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Kv
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_Kv__DD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    lnKv
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_lnKv
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    KvScaled
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_KvScaled
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    zeroJ0
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_zeroJ0
  (JNIEnv *, jclass, jint);

/*
 * Class:     func4j_special_Bessel
 * Method:    zeroJ1
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_zeroJ1
  (JNIEnv *, jclass, jint);

/*
 * Class:     func4j_special_Bessel
 * Method:    zeroJv
 * Signature: (DI)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Bessel_zeroJv
  (JNIEnv *, jclass, jdouble, jint);

/*
 * Class:     func4j_special_Bessel
 * Method:    JvAndJvDeriv
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_JvAndJvDeriv
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    YvAndYvDeriv
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_YvAndYvDeriv
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Jn
 * Signature: (IDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_Jn__IDD
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Jv
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_Jv__DDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Yn
 * Signature: (IDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_Yn__IDD
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Yv
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_Yv__DDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    In
 * Signature: (IDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_In__IDD
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Iv
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_Iv__DDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Kn
 * Signature: (IDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_Kn__IDD
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Kv
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_Kv__DDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Hn
 * Signature: (IIDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_Hn__IIDD
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Hv
 * Signature: (IDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_Hv__IDDD
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    H1n
 * Signature: (IDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_H1n__IDD
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    H1v
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_H1v__DDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    H2n
 * Signature: (IDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_H2n__IDD
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    H2v
 * Signature: (DDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_H2v__DDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Hn
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_Hn__IID
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    Hv
 * Signature: (IDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_Hv__IDD
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    H1n
 * Signature: (ID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_H1n__ID
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    H1v
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_H1v__DD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    H2n
 * Signature: (ID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_H2n__ID
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     func4j_special_Bessel
 * Method:    H2v
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Bessel_H2v__DD
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
