/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func4j_special_Clausen */

#ifndef _Included_func4j_special_Clausen
#define _Included_func4j_special_Clausen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func4j_special_Clausen
 * Method:    clausen
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Clausen_clausen
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
