/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func4j_special_ErrorFunction */

#ifndef _Included_func4j_special_ErrorFunction
#define _Included_func4j_special_ErrorFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func4j_special_ErrorFunction
 * Method:    erf
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_ErrorFunction_erf__D
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_ErrorFunction
 * Method:    erfc
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_ErrorFunction_erfc
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_ErrorFunction
 * Method:    logErfc
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_ErrorFunction_logErfc
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_ErrorFunction
 * Method:    erfZ
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_ErrorFunction_erfZ
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_ErrorFunction
 * Method:    erfQ
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_ErrorFunction_erfQ
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_ErrorFunction
 * Method:    hazard
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_ErrorFunction_hazard
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_ErrorFunction
 * Method:    erf
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_ErrorFunction_erf__DD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_ErrorFunction
 * Method:    erfDeriv
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_ErrorFunction_erfDeriv
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_ErrorFunction
 * Method:    erfAndDeriv
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_ErrorFunction_erfAndDeriv
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
