/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func4j_special_Lambert */

#ifndef _Included_func4j_special_Lambert
#define _Included_func4j_special_Lambert
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func4j_special_Lambert
 * Method:    lambertW0
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Lambert_lambertW0
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Lambert
 * Method:    lambertWm1
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Lambert_lambertWm1
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
