/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func4j_special_Coulomb */

#ifndef _Included_func4j_special_Coulomb
#define _Included_func4j_special_Coulomb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func4j_special_Coulomb
 * Method:    hydrogenicR1
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Coulomb_hydrogenicR1
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_Coulomb
 * Method:    hydrogenicR
 * Signature: (IIDD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Coulomb_hydrogenicR
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Coulomb
 * Method:    coulombWaveFunctions
 * Signature: (DDDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Coulomb_coulombWaveFunctions
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jint);

/*
 * Class:     func4j_special_Coulomb
 * Method:    coulombCL
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Coulomb_coulombCL
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
