/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func4j_special_Wright */

#ifndef _Included_func4j_special_Wright
#define _Included_func4j_special_Wright
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func4j_special_Wright
 * Method:    wrightOmega
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Wright_wrightOmega__D
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Wright
 * Method:    wrightOmega
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Wright_wrightOmega__DD
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
