/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func4j_optimize_Minimize1D */

#ifndef _Included_func4j_optimize_Minimize1D
#define _Included_func4j_optimize_Minimize1D
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func4j_optimize_Minimize1D
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_func4j_optimize_Minimize1D_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     func4j_optimize_Minimize1D
 * Method:    goldenSection
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_func4j_optimize_Minimize1D_goldenSection
  (JNIEnv *, jobject);

/*
 * Class:     func4j_optimize_Minimize1D
 * Method:    brent
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_func4j_optimize_Minimize1D_brent
  (JNIEnv *, jobject);

/*
 * Class:     func4j_optimize_Minimize1D
 * Method:    quadGolden
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_func4j_optimize_Minimize1D_quadGolden
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
