/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func4j_special_Airy */

#ifndef _Included_func4j_special_Airy
#define _Included_func4j_special_Airy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func4j_special_Airy
 * Method:    ai
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Airy_ai__D
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Airy
 * Method:    aiScaled
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Airy_aiScaled__D
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Airy
 * Method:    aiDeriv
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Airy_aiDeriv__D
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Airy
 * Method:    aiDerivScaled
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Airy_aiDerivScaled__D
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Airy
 * Method:    aiZero
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Airy_aiZero
  (JNIEnv *, jclass, jint);

/*
 * Class:     func4j_special_Airy
 * Method:    aiDerivZero
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Airy_aiDerivZero
  (JNIEnv *, jclass, jint);

/*
 * Class:     func4j_special_Airy
 * Method:    bi
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Airy_bi
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Airy
 * Method:    biScaled
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Airy_biScaled
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Airy
 * Method:    biDeriv
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Airy_biDeriv
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Airy
 * Method:    biDerivScaled
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Airy_biDerivScaled
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     func4j_special_Airy
 * Method:    biZero
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Airy_biZero
  (JNIEnv *, jclass, jint);

/*
 * Class:     func4j_special_Airy
 * Method:    biDerivZero
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_special_Airy_biDerivZero
  (JNIEnv *, jclass, jint);

/*
 * Class:     func4j_special_Airy
 * Method:    ai
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Airy_ai__DD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_Airy
 * Method:    aiScaled
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Airy_aiScaled__DD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_Airy
 * Method:    aiDeriv
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Airy_aiDeriv__DD
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     func4j_special_Airy
 * Method:    aiDerivScaled
 * Signature: (DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Airy_aiDerivScaled__DD
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
