/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func4j_special_Mathieu */

#ifndef _Included_func4j_special_Mathieu
#define _Included_func4j_special_Mathieu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func4j_special_Mathieu
 * Method:    mathieuA
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_func4j_special_Mathieu_mathieuA
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     func4j_special_Mathieu
 * Method:    mathieuB
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_func4j_special_Mathieu_mathieuB
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     func4j_special_Mathieu
 * Method:    mathieuAarray
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Mathieu_mathieuAarray
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     func4j_special_Mathieu
 * Method:    mathieuBarray
 * Signature: (IID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Mathieu_mathieuBarray
  (JNIEnv *, jclass, jint, jint, jdouble);

/*
 * Class:     func4j_special_Mathieu
 * Method:    mathieuCe
 * Signature: (IDD)I
 */
JNIEXPORT jint JNICALL Java_func4j_special_Mathieu_mathieuCe
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Mathieu
 * Method:    mathieuSe
 * Signature: (IDD)I
 */
JNIEXPORT jint JNICALL Java_func4j_special_Mathieu_mathieuSe
  (JNIEnv *, jclass, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Mathieu
 * Method:    mathieuCeArray
 * Signature: (IIDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Mathieu_mathieuCeArray
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Mathieu
 * Method:    mathieuSeArray
 * Signature: (IIDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Mathieu_mathieuSeArray
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Mathieu
 * Method:    mathieuMc
 * Signature: (IIDD)I
 */
JNIEXPORT jint JNICALL Java_func4j_special_Mathieu_mathieuMc
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Mathieu
 * Method:    mathieuMs
 * Signature: (IIDD)I
 */
JNIEXPORT jint JNICALL Java_func4j_special_Mathieu_mathieuMs
  (JNIEnv *, jclass, jint, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Mathieu
 * Method:    mathieuMcArray
 * Signature: (IIIDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Mathieu_mathieuMcArray
  (JNIEnv *, jclass, jint, jint, jint, jdouble, jdouble);

/*
 * Class:     func4j_special_Mathieu
 * Method:    mathieuMsArray
 * Signature: (IIIDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_special_Mathieu_mathieuMsArray
  (JNIEnv *, jclass, jint, jint, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
