/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class func4j_diff_NumericalDiff */

#ifndef _Included_func4j_diff_NumericalDiff
#define _Included_func4j_diff_NumericalDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     func4j_diff_NumericalDiff
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_func4j_diff_NumericalDiff_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     func4j_diff_NumericalDiff
 * Method:    central
 * Signature: (Lfunc4j/function/MathFunction;DD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_diff_NumericalDiff_central__Lfunc4j_function_MathFunction_2DD
  (JNIEnv *, jclass, jobject, jdouble, jdouble);

/*
 * Class:     func4j_diff_NumericalDiff
 * Method:    central
 * Signature: (Lfunc4j/function/MathFunction;[DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_diff_NumericalDiff_central__Lfunc4j_function_MathFunction_2_3DD
  (JNIEnv *, jclass, jobject, jdoubleArray, jdouble);

/*
 * Class:     func4j_diff_NumericalDiff
 * Method:    forward
 * Signature: (Lfunc4j/function/MathFunction;DD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_diff_NumericalDiff_forward__Lfunc4j_function_MathFunction_2DD
  (JNIEnv *, jclass, jobject, jdouble, jdouble);

/*
 * Class:     func4j_diff_NumericalDiff
 * Method:    forward
 * Signature: (Lfunc4j/function/MathFunction;[DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_diff_NumericalDiff_forward__Lfunc4j_function_MathFunction_2_3DD
  (JNIEnv *, jclass, jobject, jdoubleArray, jdouble);

/*
 * Class:     func4j_diff_NumericalDiff
 * Method:    backward
 * Signature: (Lfunc4j/function/MathFunction;DD)D
 */
JNIEXPORT jdouble JNICALL Java_func4j_diff_NumericalDiff_backward__Lfunc4j_function_MathFunction_2DD
  (JNIEnv *, jclass, jobject, jdouble, jdouble);

/*
 * Class:     func4j_diff_NumericalDiff
 * Method:    backward
 * Signature: (Lfunc4j/function/MathFunction;[DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_diff_NumericalDiff_backward__Lfunc4j_function_MathFunction_2_3DD
  (JNIEnv *, jclass, jobject, jdoubleArray, jdouble);

/*
 * Class:     func4j_diff_NumericalDiff
 * Method:    centralWithError
 * Signature: (Lfunc4j/function/MathFunction;DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_diff_NumericalDiff_centralWithError
  (JNIEnv *, jclass, jobject, jdouble, jdouble);

/*
 * Class:     func4j_diff_NumericalDiff
 * Method:    forwardWithError
 * Signature: (Lfunc4j/function/MathFunction;DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_diff_NumericalDiff_forwardWithError
  (JNIEnv *, jclass, jobject, jdouble, jdouble);

/*
 * Class:     func4j_diff_NumericalDiff
 * Method:    backwardWithError
 * Signature: (Lfunc4j/function/MathFunction;DD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_func4j_diff_NumericalDiff_backwardWithError
  (JNIEnv *, jclass, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
