/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util4j_constants_MathConstants */

#ifndef _Included_util4j_constants_MathConstants
#define _Included_util4j_constants_MathConstants
#ifdef __cplusplus
extern "C" {
#endif
#undef util4j_constants_MathConstants_M_E
#define util4j_constants_MathConstants_M_E 2.718281828459045
#undef util4j_constants_MathConstants_M_LOG2E
#define util4j_constants_MathConstants_M_LOG2E 1.4426950408889634
#undef util4j_constants_MathConstants_M_LOG10E
#define util4j_constants_MathConstants_M_LOG10E 0.4342944819032518
#undef util4j_constants_MathConstants_M_SQRT2
#define util4j_constants_MathConstants_M_SQRT2 1.4142135623730951
#undef util4j_constants_MathConstants_M_SQRT1_2
#define util4j_constants_MathConstants_M_SQRT1_2 0.7071067811865476
#undef util4j_constants_MathConstants_M_SQRT3
#define util4j_constants_MathConstants_M_SQRT3 1.7320508075688772
#undef util4j_constants_MathConstants_M_PI
#define util4j_constants_MathConstants_M_PI 3.141592653589793
#undef util4j_constants_MathConstants_M_PI_2
#define util4j_constants_MathConstants_M_PI_2 1.5707963267948966
#undef util4j_constants_MathConstants_M_PI_4
#define util4j_constants_MathConstants_M_PI_4 0.7853981633974483
#undef util4j_constants_MathConstants_M_SQRTPI
#define util4j_constants_MathConstants_M_SQRTPI 1.772453850905516
#undef util4j_constants_MathConstants_M_2_SQRTPI
#define util4j_constants_MathConstants_M_2_SQRTPI 1.1283791670955126
#undef util4j_constants_MathConstants_M_1_PI
#define util4j_constants_MathConstants_M_1_PI 0.3183098861837907
#undef util4j_constants_MathConstants_M_2_PI
#define util4j_constants_MathConstants_M_2_PI 0.6366197723675814
#undef util4j_constants_MathConstants_M_LN10
#define util4j_constants_MathConstants_M_LN10 2.302585092994046
#undef util4j_constants_MathConstants_M_LN2
#define util4j_constants_MathConstants_M_LN2 0.6931471805599453
#undef util4j_constants_MathConstants_M_LNPI
#define util4j_constants_MathConstants_M_LNPI 1.1447298858494002
#undef util4j_constants_MathConstants_M_EULER
#define util4j_constants_MathConstants_M_EULER 0.5772156649015329
/*
 * Class:     util4j_constants_MathConstants
 * Method:    gslposinf
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_util4j_constants_MathConstants_gslposinf
  (JNIEnv *, jclass);

/*
 * Class:     util4j_constants_MathConstants
 * Method:    gslneginf
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_util4j_constants_MathConstants_gslneginf
  (JNIEnv *, jclass);

/*
 * Class:     util4j_constants_MathConstants
 * Method:    gslnan
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_util4j_constants_MathConstants_gslnan
  (JNIEnv *, jclass);

/*
 * Class:     util4j_constants_MathConstants
 * Method:    isNaN
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_util4j_constants_MathConstants_isNaN
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     util4j_constants_MathConstants
 * Method:    isInf
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_util4j_constants_MathConstants_isInf
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     util4j_constants_MathConstants
 * Method:    isPositiveInf
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_util4j_constants_MathConstants_isPositiveInf
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     util4j_constants_MathConstants
 * Method:    isNegativeInf
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_util4j_constants_MathConstants_isNegativeInf
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     util4j_constants_MathConstants
 * Method:    isFinite
 * Signature: (D)Z
 */
JNIEXPORT jboolean JNICALL Java_util4j_constants_MathConstants_isFinite
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
