/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ode4j_OdeSystemSolver */

#ifndef _Included_ode4j_OdeSystemSolver
#define _Included_ode4j_OdeSystemSolver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ode4j_OdeSystemSolver_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rk2
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ode4j_OdeSystemSolver_rk2__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rk2
 * Signature: ([D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ode4j_OdeSystemSolver_rk2___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rk4
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ode4j_OdeSystemSolver_rk4__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rk4
 * Signature: ([D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ode4j_OdeSystemSolver_rk4___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rkf45
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ode4j_OdeSystemSolver_rkf45__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rkf45
 * Signature: ([D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ode4j_OdeSystemSolver_rkf45___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rkck
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ode4j_OdeSystemSolver_rkck__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rkck
 * Signature: ([D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ode4j_OdeSystemSolver_rkck___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rk8pd
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ode4j_OdeSystemSolver_rk8pd__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rk8pd
 * Signature: ([D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ode4j_OdeSystemSolver_rk8pd___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rk1imp
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ode4j_OdeSystemSolver_rk1imp__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rk1imp
 * Signature: ([D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ode4j_OdeSystemSolver_rk1imp___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rk2imp
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ode4j_OdeSystemSolver_rk2imp__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rk2imp
 * Signature: ([D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ode4j_OdeSystemSolver_rk2imp___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rk4imp
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ode4j_OdeSystemSolver_rk4imp__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    rk4imp
 * Signature: ([D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ode4j_OdeSystemSolver_rk4imp___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    bsimp
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ode4j_OdeSystemSolver_bsimp__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    bsimp
 * Signature: ([D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ode4j_OdeSystemSolver_bsimp___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    msadams
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ode4j_OdeSystemSolver_msadams__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    msadams
 * Signature: ([D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ode4j_OdeSystemSolver_msadams___3D
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    msbdf
 * Signature: (D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ode4j_OdeSystemSolver_msbdf__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ode4j_OdeSystemSolver
 * Method:    msbdf
 * Signature: ([D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_ode4j_OdeSystemSolver_msbdf___3D
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
