/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class seq4j_LevinTransform */

#ifndef _Included_seq4j_LevinTransform
#define _Included_seq4j_LevinTransform
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     seq4j_LevinTransform
 * Method:    sumLevinUaccel
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_seq4j_LevinTransform_sumLevinUaccel
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     seq4j_LevinTransform
 * Method:    sumLevinUtruncAccel
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_seq4j_LevinTransform_sumLevinUtruncAccel
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
