/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class seq4j_QuasiRandomSequence */

#ifndef _Included_seq4j_QuasiRandomSequence
#define _Included_seq4j_QuasiRandomSequence
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     seq4j_QuasiRandomSequence
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_seq4j_QuasiRandomSequence_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     seq4j_QuasiRandomSequence
 * Method:    niederreiter2
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_seq4j_QuasiRandomSequence_niederreiter2
  (JNIEnv *, jobject, jint);

/*
 * Class:     seq4j_QuasiRandomSequence
 * Method:    sobol
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_seq4j_QuasiRandomSequence_sobol
  (JNIEnv *, jobject, jint);

/*
 * Class:     seq4j_QuasiRandomSequence
 * Method:    halton
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_seq4j_QuasiRandomSequence_halton
  (JNIEnv *, jobject, jint);

/*
 * Class:     seq4j_QuasiRandomSequence
 * Method:    reverseHalton
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_seq4j_QuasiRandomSequence_reverseHalton
  (JNIEnv *, jobject, jint);

/*
 * Class:     seq4j_QuasiRandomSequence
 * Method:    niederreiter2All
 * Signature: (I)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_seq4j_QuasiRandomSequence_niederreiter2All
  (JNIEnv *, jobject, jint);

/*
 * Class:     seq4j_QuasiRandomSequence
 * Method:    sobolAll
 * Signature: (I)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_seq4j_QuasiRandomSequence_sobolAll
  (JNIEnv *, jobject, jint);

/*
 * Class:     seq4j_QuasiRandomSequence
 * Method:    haltonAll
 * Signature: (I)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_seq4j_QuasiRandomSequence_haltonAll
  (JNIEnv *, jobject, jint);

/*
 * Class:     seq4j_QuasiRandomSequence
 * Method:    reverseHaltonAll
 * Signature: (I)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_seq4j_QuasiRandomSequence_reverseHaltonAll
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
